server:
  port: 8080
spring:
  boot:
    message: Hello, Department Service
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      hbm2ddl:
          auto: create
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
